<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DummyUserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name' => 'Budi Santoso',
                'username' => 'budi.santoso',
                'gender' => 'Laki-laki',
                'tanggal_lahir' => '1995-03-12',
                'email' => 'budi.santoso@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174011203950001',
                'no_hp' => '081234567801',
                'alamat' => 'Jl. Merdeka No. 10',
                'city' => 'Jakarta',
                'postal_code' => '10110',
                'rt' => '001',
                'rw' => '002',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Siti Aisyah',
                'username' => 'siti.aisyah',
                'gender' => 'Perempuan',
                'tanggal_lahir' => '1997-07-21',
                'email' => 'siti.aisyah@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174012107970002',
                'no_hp' => '081234567802',
                'alamat' => 'Jl. Melati No. 5',
                'city' => 'Bandung',
                'postal_code' => '40115',
                'rt' => '002',
                'rw' => '003',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Andi Pratama',
                'username' => 'andi.pratama',
                'gender' => 'Laki-laki',
                'tanggal_lahir' => '1993-11-08',
                'email' => 'andi.pratama@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174010811930003',
                'no_hp' => '081234567803',
                'alamat' => 'Jl. Kenanga No. 17',
                'city' => 'Surabaya',
                'postal_code' => '60231',
                'rt' => '003',
                'rw' => '001',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dewi Lestari',
                'username' => 'dewi.lestari',
                'gender' => 'Perempuan',
                'tanggal_lahir' => '1998-01-25',
                'email' => 'dewi.lestari@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174012501980004',
                'no_hp' => '081234567804',
                'alamat' => 'Jl. Anggrek No. 23',
                'city' => 'Semarang',
                'postal_code' => '50134',
                'rt' => '004',
                'rw' => '005',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Rizky Hidayat',
                'username' => 'rizky.hidayat',
                'gender' => 'Laki-laki',
                'tanggal_lahir' => '1994-05-14',
                'email' => 'rizky.hidayat@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174011405940005',
                'no_hp' => '081234567805',
                'alamat' => 'Jl. Mawar No. 8',
                'city' => 'Yogyakarta',
                'postal_code' => '55281',
                'rt' => '005',
                'rw' => '004',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nabila Putri',
                'username' => 'nabila.putri',
                'gender' => 'Perempuan',
                'tanggal_lahir' => '2000-09-03',
                'email' => 'nabila.putri@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174010309000006',
                'no_hp' => '081234567806',
                'alamat' => 'Jl. Flamboyan No. 11',
                'city' => 'Malang',
                'postal_code' => '65119',
                'rt' => '006',
                'rw' => '002',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Fajar Nugroho',
                'username' => 'fajar.nugroho',
                'gender' => 'Laki-laki',
                'tanggal_lahir' => '1992-12-19',
                'email' => 'fajar.nugroho@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174011912920007',
                'no_hp' => '081234567807',
                'alamat' => 'Jl. Cendana No. 14',
                'city' => 'Bekasi',
                'postal_code' => '17121',
                'rt' => '007',
                'rw' => '006',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Maya Sari',
                'username' => 'maya.sari',
                'gender' => 'Perempuan',
                'tanggal_lahir' => '1996-04-28',
                'email' => 'maya.sari@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174012804960008',
                'no_hp' => '081234567808',
                'alamat' => 'Jl. Kamboja No. 19',
                'city' => 'Depok',
                'postal_code' => '16412',
                'rt' => '008',
                'rw' => '003',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Arif Rahman',
                'username' => 'arif.rahman',
                'gender' => 'Laki-laki',
                'tanggal_lahir' => '1991-08-30',
                'email' => 'arif.rahman@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174013008910009',
                'no_hp' => '081234567809',
                'alamat' => 'Jl. Wijaya Kusuma No. 6',
                'city' => 'Bogor',
                'postal_code' => '16128',
                'rt' => '009',
                'rw' => '001',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Intan Permata',
                'username' => 'intan.permata',
                'gender' => 'Perempuan',
                'tanggal_lahir' => '1999-06-16',
                'email' => 'intan.permata@example.com',
                'password' => Hash::make('password123'),
                'role' => 'warga',
                'nik' => '3174011606990010',
                'no_hp' => '081234567810',
                'alamat' => 'Jl. Dahlia No. 27',
                'city' => 'Tangerang',
                'postal_code' => '15118',
                'rt' => '010',
                'rw' => '005',
                'email_verified_at' => now(),
            ],
        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['email' => $user['email']],
                $user
            );
        }
    }
}
